import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import CounterModule from "./components/counterComponent";
import "./globals.css";
import Footer from "./components/footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full antialiased">
			<body className="min-h-full flex flex-col">
				<NextIntlClientProvider>{children}</NextIntlClientProvider>
				<Footer />
				<CounterModule />
			</body>
		</html>
	);
}
